Repository ALLATRA-IT/ephyr, pull requests merged in 2022-08, with the labels that each got.

#197 Add file record test
  components/restreamer/CHANGELOG.md
  components/restreamer/client/cypress/integration/add_output_file.js
  components/restreamer/client/cypress/integration/add_output_mixin.js
  components/restreamer/client/cypress/integration/add_output_multiple.js
  components/restreamer/client/cypress/integration/add_output_single.js
  components/restreamer/client/cypress/integration/all_outputs_start.js
  components/restreamer/client/cypress/integration/all_outputs_stop.js
  components/restreamer/client/cypress/integration/check_file_recording.js
  components/restreamer/client/cypress/integration/check_streaming_state.js
  components/restreamer/client/cypress/support/commands.js
Labels: autotest

#203 Feature/ Mixin sidechain
  components/restreamer/CHANGELOG.md
  components/restreamer/client.graphql.schema.json
  components/restreamer/client/api/client.graphql
  components/restreamer/client/api/mix.graphql
  components/restreamer/client/cypress/integration/add_output_multiple_mixin.js
  components/restreamer/client/cypress/support/commands.js
  components/restreamer/client/package.json
  components/restreamer/client/src/components/AppMix.svelte
  components/restreamer/client/src/components/Mixin.svelte
  components/restreamer/client/src/components/Output.svelte
  components/restreamer/client/src/components/Restream.svelte
  components/restreamer/client/static/dashboard/index.html
  components/restreamer/client/static/index.html
  components/restreamer/client/static/mix/index.html
  components/restreamer/client/yarn.lock
  components/restreamer/mix.graphql.schema.json
  components/restreamer/src/api/graphql/client.rs
  components/restreamer/src/api/graphql/mix.rs
  components/restreamer/src/ffmpeg/mixing_restreamer.rs
  components/restreamer/src/spec/v1.rs
  components/restreamer/src/state.rs
Labels: enhancement

#204 Exit FFmpeg gracefully
  Cargo.lock
  components/restreamer/CHANGELOG.md
  components/restreamer/Cargo.toml
  components/restreamer/client/cypress/integration/check_streaming_state.js
  components/restreamer/client/cypress/support/commands.js
  components/restreamer/client/src/components/InputEndpoint.svelte
  components/restreamer/src/ffmpeg/mixing_restreamer.rs
  components/restreamer/src/ffmpeg/restreamer.rs
  components/restreamer/src/ffmpeg/restreamer_kind.rs
Labels: enhancement

#212 Change Delay without restart FFmpeg in Restreamer Mixin
  components/restreamer/CHANGELOG.md
  components/restreamer/client/cypress/integration/check_streaming_state.js
  components/restreamer/src/ffmpeg/mixing_restreamer.rs
Labels: enhancement

#214 Refactor state.rs
  components/restreamer/src/ffmpeg.rs
  components/restreamer/src/state.rs
  components/restreamer/src/state/client_statistics.rs
  components/restreamer/src/state/input.rs
  components/restreamer/src/state/input/input_endpoint.rs
  components/restreamer/src/state/input/input_src.rs
  components/restreamer/src/state/label.rs
  components/restreamer/src/state/output.rs
  components/restreamer/src/state/output/mixin.rs
  components/restreamer/src/state/output/volume.rs
  components/restreamer/src/state/restream.rs
  components/restreamer/src/state/settings.rs
Labels: debt::tech, comp::restreamer
